import { createElement as h } from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import QRCode from "qrcode";
import { formatMoney, formatDate, shortHash } from "@/lib/utils";

export interface PayslipData {
  company: string;
  number: string;
  verifyUrl: string;
  employee: { name: string; email: string; country: string; jobTitle?: string | null };
  month: string;
  gross: number;
  tax: number;
  net: number;
  currency: string;
  stablecoinAmount: number;
  stablecoin: string;
  /** USD value of the payout, captured at settlement time (CoinGecko). */
  usdAmount?: number | null;
  /** CKB/USD rate at settlement time. */
  usdRate?: number | null;
  txHash: string;
  paidAt: Date | null;
}

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 10, color: "#1e1b2e", fontFamily: "Helvetica" },
  row: { flexDirection: "row", justifyContent: "space-between" },
  brand: { fontSize: 18, fontFamily: "Helvetica-Bold", color: "#7c5cff" },
  muted: { color: "#6b7280" },
  h2: { fontSize: 12, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  card: { border: "1px solid #e5e7eb", borderRadius: 6, padding: 14, marginTop: 14 },
  line: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 4 },
  sep: { borderTop: "1px solid #e5e7eb", marginVertical: 6 },
  bold: { fontFamily: "Helvetica-Bold" },
  net: { fontSize: 14, fontFamily: "Helvetica-Bold", color: "#16a34a" },
  badge: { backgroundColor: "#ecfdf5", color: "#16a34a", padding: "3 8", borderRadius: 10, fontSize: 9, fontFamily: "Helvetica-Bold" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#9ca3af", textAlign: "center" },
  qr: { width: 84, height: 84 },
  mono: { fontFamily: "Courier" },
});

export async function buildPayslipPdf(d: PayslipData): Promise<Uint8Array> {
  const qr = await QRCode.toDataURL(d.verifyUrl, { margin: 1, width: 200 });

  const doc = h(
    Document,
    {},
    h(
      Page,
      { size: "A4", style: s.page },
      // Header
      h(
        View,
        { style: [s.row, { alignItems: "flex-start" }] },
        h(
          View,
          {},
          h(Text, { style: s.brand }, d.company),
          h(Text, { style: [s.muted, { marginTop: 2 }] }, "Payslip · " + d.number),
        ),
        h(
          View,
          { style: { alignItems: "flex-end" } },
          h(Text, { style: s.h2 }, "Pay period"),
          h(Text, { style: s.muted }, d.month),
        ),
      ),

      // Employee
      h(
        View,
        { style: s.card },
        h(Text, { style: s.h2 }, "Employee"),
        h(Text, { style: s.bold }, d.employee.name),
        h(Text, { style: s.muted }, d.employee.email),
        h(Text, { style: s.muted }, (d.employee.jobTitle ? d.employee.jobTitle + " · " : "") + d.employee.country),
      ),

      // Breakdown
      h(
        View,
        { style: s.card },
        h(Text, { style: s.h2 }, "Salary breakdown"),
        h(View, { style: s.line }, h(Text, {}, "Gross pay"), h(Text, {}, formatMoney(d.gross, d.currency))),
        h(View, { style: s.line }, h(Text, {}, "Tax withheld"), h(Text, {}, "-" + formatMoney(d.tax, d.currency))),
        h(View, { style: s.sep }),
        h(View, { style: s.line }, h(Text, { style: s.bold }, "Net pay"), h(Text, { style: s.net }, formatMoney(d.net, d.currency))),
        h(
          View,
          { style: [s.line, { marginTop: 4 }] },
          h(Text, { style: s.muted }, "Paid in " + d.stablecoin),
          h(
            Text,
            { style: s.bold },
            formatMoney(d.stablecoinAmount, d.stablecoin) +
              (d.usdAmount != null ? "  (≈ " + formatMoney(d.usdAmount, "USD") + ")" : ""),
          ),
        ),
        d.usdRate != null
          ? h(
              View,
              { style: s.line },
              h(Text, { style: s.muted }, "CKB/USD rate at settlement"),
              h(Text, { style: s.muted }, "$" + d.usdRate.toFixed(6) + " (CoinGecko)"),
            )
          : null,
      ),

      // Payment proof + QR
      h(
        View,
        { style: [s.card, s.row, { alignItems: "center" }] },
        h(
          View,
          { style: { flex: 1 } },
          h(Text, { style: s.h2 }, "Payment proof"),
          h(View, { style: { marginBottom: 4 } }, h(Text, { style: s.badge }, "SETTLED ON FIBER")),
          h(Text, { style: s.muted }, "Fiber payment hash"),
          h(Text, { style: s.mono }, shortHash(d.txHash, 14, 12)),
          h(Text, { style: [s.muted, { marginTop: 4 }] }, "Date: " + (d.paidAt ? formatDate(d.paidAt, true) : "—")),
        ),
        h(
          View,
          { style: { alignItems: "center" } },
          h(Image, { src: qr, style: s.qr }),
          h(Text, { style: [s.muted, { fontSize: 7, marginTop: 3 }] }, "Scan to verify"),
        ),
      ),

      h(Text, { style: s.footer }, "Generated by Fiber Payroll · Settled over the Nervos CKB Fiber Network · " + d.verifyUrl),
    ),
  );

  return renderToBuffer(doc as Parameters<typeof renderToBuffer>[0]);
}
